### ISSUE TITLE
App does not work

### ISSUE THREAD

**Issue by cikavladimir** [glenasmith/pluralsight-primeng#7]
```
ng serve -o
Your global Angular CLI version (6.0.8) is greater than your local
version (1.5.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/mac/programming/angular/plural/pluralsight-primeng/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by tehcmanmax** [comment]
Check that the "@angular-devkit/core" package is installed in your project. You can do this by checking the "dependencies" section of your project's package.json file.

If the package is missing, you can try installing it by running the following command in your project directory:

css
Copy code
npm install --save-dev @angular-devkit/core
This should install the package and add it to your project's dependencies.

If the package is already installed but you are still seeing the error message, you can try deleting your project's "node_modules" directory and then running npm install again to reinstall all dependencies.

If none of the above steps work, you may need to reinstall the Angular CLI globally. You can do this by running the following command:

sql
Copy code
npm uninstall -g @angular/cli
npm cache clean --force
npm install -g @angular/cli
This will uninstall and then reinstall the Angular CLI globally on your system.
